import {
  Worker,
  Escrow,
  Milestone,
  Verification,
  Activity,
  DashboardStats,
} from "@/lib/types"

// Mock Workers
export const mockWorkers: Worker[] = [
  {
    id: "w1",
    name: "Agent Worker Alpha",
    type: "agent",
    status: "active",
    reputation: 4.9,
    completedJobs: 127,
    successRate: 98,
    specialization: "Web Development",
    walletAddress: "0x1234...5678",
    joinedAt: new Date("2024-01-15"),
    totalEarnings: 125000,
  },
  {
    id: "w2",
    name: "Human Worker Beta",
    type: "human",
    status: "active",
    reputation: 4.7,
    completedJobs: 89,
    successRate: 95,
    specialization: "Content Writing",
    walletAddress: "0x8765...4321",
    joinedAt: new Date("2024-02-20"),
    totalEarnings: 78500,
  },
  {
    id: "w3",
    name: "Agent Worker Gamma",
    type: "agent",
    status: "active",
    reputation: 4.8,
    completedJobs: 203,
    successRate: 97,
    specialization: "Mobile Development",
    walletAddress: "0x5555...6666",
    joinedAt: new Date("2023-11-10"),
    totalEarnings: 215000,
  },
  {
    id: "w4",
    name: "Human Worker Delta",
    type: "human",
    status: "active",
    reputation: 4.6,
    completedJobs: 156,
    successRate: 92,
    specialization: "UI/UX Design",
    walletAddress: "0x7777...8888",
    joinedAt: new Date("2024-03-05"),
    totalEarnings: 142000,
  },
]

// Mock Milestones
export const mockMilestones: Milestone[] = [
  {
    id: "m1",
    escrowId: "e1",
    title: "Project Setup & Architecture",
    description: "Initial setup, database design, and architecture planning",
    order: 1,
    status: "completed",
    amount: 1000,
    dueDate: new Date("2024-05-10"),
    completedAt: new Date("2024-05-08"),
    proofUrl: "https://github.com/repo/commits/abc123",
  },
  {
    id: "m2",
    escrowId: "e1",
    title: "Backend API Development",
    description: "Build REST API endpoints with authentication",
    order: 2,
    status: "in-progress",
    amount: 2000,
    dueDate: new Date("2024-05-24"),
  },
  {
    id: "m3",
    escrowId: "e1",
    title: "Frontend Implementation",
    description: "React components and UI implementation",
    order: 3,
    status: "pending",
    amount: 1500,
    dueDate: new Date("2024-06-07"),
  },
  {
    id: "m4",
    escrowId: "e1",
    title: "Testing & Deployment",
    description: "Full test suite and production deployment",
    order: 4,
    status: "pending",
    amount: 500,
    dueDate: new Date("2024-06-14"),
  },
  {
    id: "m5",
    escrowId: "e2",
    title: "Content Outline",
    description: "Create detailed outline for 50 articles",
    order: 1,
    status: "completed",
    amount: 500,
    dueDate: new Date("2024-05-05"),
    completedAt: new Date("2024-05-04"),
  },
  {
    id: "m6",
    escrowId: "e2",
    title: "First Draft Articles",
    description: "Write first 25 articles",
    order: 2,
    status: "completed",
    amount: 1000,
    dueDate: new Date("2024-05-19"),
    completedAt: new Date("2024-05-18"),
  },
  {
    id: "m7",
    escrowId: "e2",
    title: "Final Articles & SEO",
    description: "Complete remaining 25 articles with SEO optimization",
    order: 3,
    status: "completed",
    amount: 1000,
    dueDate: new Date("2024-05-30"),
    completedAt: new Date("2024-05-29"),
  },
]

// Mock Verifications
export const mockVerifications: Verification[] = [
  {
    id: "v1",
    escrowId: "e1",
    milestoneId: "m1",
    status: "verified",
    aiScore: 0.95,
    reviewedAt: new Date("2024-05-08"),
    createdAt: new Date("2024-05-08"),
  },
  {
    id: "v2",
    escrowId: "e2",
    milestoneId: "m5",
    status: "verified",
    aiScore: 0.92,
    reviewedAt: new Date("2024-05-04"),
    createdAt: new Date("2024-05-04"),
  },
  {
    id: "v3",
    escrowId: "e2",
    milestoneId: "m6",
    status: "verified",
    aiScore: 0.88,
    reviewedAt: new Date("2024-05-18"),
    createdAt: new Date("2024-05-18"),
  },
  {
    id: "v4",
    escrowId: "e2",
    milestoneId: "m7",
    status: "verified",
    aiScore: 0.91,
    reviewedAt: new Date("2024-05-29"),
    createdAt: new Date("2024-05-29"),
  },
]

// Mock Escrows
export const mockEscrows: Escrow[] = [
  {
    id: "e1",
    title: "Web Development Project",
    description: "Build a full-stack web application with React and Node.js",
    status: "in_progress", // Changed from "active" to "in_progress"
    clientId: "c1",
    workerId: "w1",
    amount: 5000,
    currency: "USD",
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-15"),
    startDate: new Date("2024-05-01"),
    endDate: new Date("2024-06-14"),
    milestones: mockMilestones.filter((m) => m.escrowId === "e1"),
    verifications: mockVerifications.filter((v) => v.escrowId === "e1"),
    totalMilestonesCompleted: 1,
    totalMilestones: 4,
  },
  {
    id: "e2",
    title: "AI Content Generation",
    description: "Write 50 high-quality blog articles about AI and Machine Learning",
    status: "released", // Changed from "completed" to "released"
    clientId: "c2",
    workerId: "w2",
    amount: 2500,
    currency: "USD",
    createdAt: new Date("2024-04-15"),
    updatedAt: new Date("2024-05-29"),
    startDate: new Date("2024-04-15"),
    endDate: new Date("2024-05-30"),
    milestones: mockMilestones.filter((m) => m.escrowId === "e2"),
    verifications: mockVerifications.filter((v) => v.escrowId === "e2"),
    totalMilestonesCompleted: 3,
    totalMilestones: 3,
  },
  {
    id: "e3",
    title: "Mobile App Development",
    description: "Develop a cross-platform mobile application for iOS and Android",
    status: "draft", // Changed from "pending" to "draft"
    clientId: "c3",
    workerId: "w3",
    amount: 8000,
    currency: "USD",
    createdAt: new Date("2024-05-16"),
    updatedAt: new Date("2024-05-16"),
    startDate: undefined,
    endDate: undefined,
    milestones: [],
    verifications: [],
    totalMilestonesCompleted: 0,
    totalMilestones: 0,
  },
]

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: "a1",
    type: "milestone_completed",
    escrowId: "e1",
    title: "Milestone Completed",
    description: "Project Setup & Architecture milestone completed",
    actor: "w1",
    timestamp: new Date("2024-05-08T14:30:00"),
  },
  {
    id: "a2",
    type: "verification_passed",
    escrowId: "e1",
    title: "Verification Passed",
    description: "AI verification passed with 95% confidence score",
    actor: "system",
    timestamp: new Date("2024-05-08T16:45:00"),
  },
  {
    id: "a3",
    type: "funds_released",
    escrowId: "e2",
    title: "Funds Released",
    description: "All escrow funds released to worker after final verification",
    actor: "system",
    timestamp: new Date("2024-05-30T10:15:00"),
  },
  {
    id: "a4",
    type: "escrow_created",
    escrowId: "e3",
    title: "Escrow Created",
    description: "New escrow created for Mobile App Development",
    actor: "c3",
    timestamp: new Date("2024-05-16T09:00:00"),
  },
]

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalEscrows: 3,
  activeEscrows: 1, // e1 is in_progress
  completedEscrows: 1, // e2 is released
  totalValue: 15500,
  milestonesCompleted: 4,
  totalMilestones: 7,
  averageVerificationScore: 0.915,
  activeWorkers: 4,
}
